### ISSUE TITLE
Add link to gobwas/ws (the actual code)

### ISSUE THREAD

**Issue by alexhultman** [eranyanay/1m-go-websockets#2]
This repo is trending so it makes sense to link the library you used to get these good results, I think they could use the traffic also.

https://github.com/gobwas/ws

**Comment by eranyanay** [comment]
I think its quite clear from the slides/talk that the additional improvements are indeed as a result of the great design in this library
But I will push later on a few readme notes per example that explains the specific example with links to any resource or library used.

**Comment by alexhultman** [comment]
Obviously it is clear if you loot around the repo, but most people who visit GitHub repos that are trending will star-and-leave (patent pending). A prominent link would make it a lot more probable they also star gobwas/ws, which is a lot more interesting of a project. I bet 90% of people coming here believe THIS repo is where the perf. stem from, when THIS repo is merely a use case for gobwas/ws.

**Comment by eranyanay** [comment]
I dont think you can say one repo is more interesting than the other, its not something that can be compared as both repos serves completely different purposes

This repo simply demonstrates, through a series of examples, how to optimize a very naive (yet super common) usage of websockets in Go, in order to achieve a specific goal. 
Using gobwas/ws alone wont give you a complete solution for that, and more things are required (all of them are listed in this repo)

I cant say what people believe when they visit this repo, but I do think that if they go through the slides and examples its quite clear what serves what role.

I also believe that many of the interest is because this repo shows a **complete** example that demonstrates in full all the tiny details of what is needed and how to overcome any issue that arises.

**Comment by alexhultman** [comment]
Well the main component here is clearly gobwas/ws and yes, you can easily reach 1 million websockets with it alone. Slightly higher memory usage but still reasonable and faster since you skip the extra epoll syscalls.

That's the main component and the main invention here. Everything else is basically Linux sysadmin stuff you can find 1 Google search away.
